:Author: subhradeep2002
:Email: Myfamily9476@gmail.com
:Date: 30/07/2023
:Revision: version# 3.17
:License: Public Domain

= Project: Automation

project Description

== Step 1: Installation

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram image provided in the Readme file.

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── main.ino            => main Arduino file
  ├── thingsProperties    => Variables and mechanism for the logic 
  ├── arduino_secrets     => Wifi details
  ├── sketch.json         => Operations for hardware
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a GNU 3.0 Public License.

=== Contributing
To contribute to this project please contact me. Details are provided here. 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name            | Quantity
| M1 | ESP8266              | 1
| R1 | Relay                | 4
| R2 | 1K ohm Resistor      | 5
| R3 | 220 ohm Resistor     | 4
| T1 | 3 pin Screw terminal | 4
| T2 | 2 pin Screw terminal | 1
| D1 | Diode                | 5
| L1 | LED                  | 5
| C1 | 100 nf Capasitor     | 2
| V1 | L7805                | 1
| A1 | Heat shink           | 1
| C2 | DC jack              | 1
| C3 | Female header        | 40
| A2 | PCB                  | 1
     
|===


=== Help
Feel free to contact me if you face any deficulty.
